server:
  port: 8081

spring:
  application:
    name: til-service
  config:
    import: optional:configserver:http://ec2-15-164-164-245.ap-northeast-2.compute.amazonaws.com:8888
  cloud:
    config:
      name: secret
  profiles:
    active: dev
  servlet:
    multipart:
      file-size-threshold: 1MB
      max-file-size: 5MB
      max-request-size: 50MB
#  jpa:
#    hibernate:
#      ddl-auto: update

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://ec2-15-164-164-245.ap-northeast-2.compute.amazonaws.com:8761

      
file:
  profileDir: save-profile
  boardDir: save-board-imgs
