server:
  port: 8081

spring:
  application:
    name: til-service
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      name: secret
  profiles:
    active: dev
  servlet:
    multipart:
      file-size-threshold: 1MB
      max-file-size: 5MB
      max-request-size: 50MB

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

      
file:
  profileDir: save-profile
  boardDir: save-board-imgs
